from enum import Enum


class Mercury(str, Enum):
    MERCURY_REDSTONE_3 = "MERCURY_REDSTONE_3"
    MERCURY_REDSTONE_4 = "MERCURY_REDSTONE_4"
    MERCURY_ATLAS_6 = "MERCURY_ATLAS_6"
    MERCURY_ATLAS_7 = "MERCURY_ATLAS_7"
    MERCURY_ATLAS_8 = "MERCURY_ATLAS_8"
    MERCURY_ATLAS_9 = "MERCURY_ATLAS_9"
